- name: Kalliope Google Maps neuron
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install gmaps pip dependencies"
      pip:
        name: googlemaps
        version: 2.5.1
    - name: "Install beautifulsoup pip dependencies"
      pip:
        name: beautifulsoup4
        version: 4.6.0
